FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /app

RUN git clone https://github.com/Ant198/formSubmissionTest.git /app

COPY POM.xml .

RUN mvn clean test

CMD ["/bin/sh", "-c", "mvn clean test && cp target/surefire-reports/testng-results.xml /app/testng-results.xml"]


