version: '3'
services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    restart: always
    ports:
      - "4444:4444"
    networks:
      - test-network

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-runner
    depends_on:
      - selenium
    networks:
      - test-network
    watch:
      test-runner:
        paths:
          - ./src
          - ./pom.xml
        action: rebuild

volumes:
  jenkins_home:

networks:
  test-network: