services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - '8080:8080'
    networks:
      - default
    volumes:
      - '/docker/jenkins/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '~/.m2:/root/.m2'

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    restart: always
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - test-network

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test-runner
    container_name: test-runner
    depends_on:
      - selenium
    networks:
      - test-network
    #volumes:
   #   - .:/app

volumes:
  jenkins_home:

networks:
  test-network: