services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - '8080:8080'
    networks:
      - default
    volumes:
      - '/docker/jenkins/jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '~/.m2:/root/.m2'

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    restart: always
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - test-network


  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/allure-results:/app/allure-results
      - ${PWD}/allure-reports:/app/default-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test-runner
    container_name: test-runner
    depends_on:
      - selenium
    networks:
      - test-network

volumes:
  jenkins_home:

networks:
  test-network: