version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Даємо Jenkins доступ до Docker
    networks:
        - test-network

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    restart: always
    ports:
      - "4444:4444"
    networks:
      - test-network

  test:
    build: .
    container_name: test_form_c
    depends_on:
      - selenium
    environment:
      - SELENIUM_GRID_URL=http://selenium:4444/wd/hub
    networks:
      - test-network

volumes:
  jenkins_home:

networks:
  test-network: