version: '3'
services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    restart: always
    ports:
      - "4444:4444"
    networks:
      - test-network

volumes:
  jenkins_home:

networks:
  test-network: